language: cpp
compiler:
    - gcc

os:    
    - osx

# use containers
sudo: false

env:
  - TYPE=Release DEVSPACE=$TRAVIS_BUILD_DIR/..

install:
  #dcmtk  
  - cd $DEVSPACE
  - wget http://draconpern-buildcache.s3.amazonaws.com/dcmtk-$TRAVIS_OS_NAME.zip
  - unzip dcmtk-$TRAVIS_OS_NAME.zip

  #openjpeg
  - cd $DEVSPACE
  - wget https://github.com/uclouvain/openjpeg/archive/version.2.1.tar.gz
  - tar -xzf version.2.1.tar.gz
  - mv openjpeg-version.2.1 openjpeg
  - cd openjpeg && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. -DBUILD_SHARED_LIBS=0 -DCMAKE_INSTALL_PREFIX=$DEVSPACE/openjpeg/$TYPE
  - make -j8 install

script:
  - cd $TRAVIS_BUILD_DIR && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. -DBUILD_SHARED_LIBS=OFF -DOPENJPEG=$DEVSPACE/openjpeg/$TYPE -DDCMTK_DIR=$DEVSPACE/dcmtk/$TYPE -DCMAKE_INSTALL_PREFIX=$DEVSPACE/fmjpeg2koj/$TYPE 
  - make -j8 install
before_deploy:
- cd $DEVSPACE
- zip -r latest.zip fmjpeg2koj/$TYPE openjpeg/$TYPE
- mkdir -p dpl_cd_upload
- mv latest.zip $DEVSPACE/dpl_cd_upload/fmjpeg2koj-$TRAVIS_OS_NAME.zip
deploy:
  provider: s3
  access_key_id: AKIAJLIJS2MGONMUBW4A
  secret_access_key:
    secure:  txxaZanyyfYyJk9LRYANhCsG89mqkHYQkZF4jJk0ZE8AGMg7nPsMm6VtAiX9sOJOMBQeetLSyx6AtyYmdnuBiTvbfqgIcl/v1fowoOLuHJ09lulxMw7Iuc1/NZhnlKDcsZDWeaGrk5vnjMkS5xm7iINAYBt1xFVh9QaMpQACe4MdIGLP7lM/ckmF8hAzCMpX0YWNk5sF6y8LCVqlHzD7CD6c3ApAzZqGmQzjR2qjwK0qzBciPXbQA5CLgPDu4Ytt5GJ0GFMiBCMvkOUmFREy2HdFsFADKlk2aluI3+77IWcGFBl68+49nFy8Q5Qt8tU7GKieqKGUVGyr4pR+ZqFyoMlkx8nPNMMOfTio9Y+AYkTIw1y2YJ7sTSn/NpeBdZwo2yeXFQrusqtL/CkkyAQ5t5ZFDK7132aoOVBsXlB0uhwezZP5Mwc64X7uYzmHaEB2CepYlSPd+YoActZwdl32eS5kb+QQbcXuipFUfQCa0cklYJ3PmfR+yKJcF9zMWqKn+t1zRZHXOmNAVqJHiUDXtyXS5cUA9jADhiysGmVU1QqsOYnSX0ocG8UT3xY0VoevNd2r5MnA3Wy4p4e7lKlL84yPI+2h6LqvD3VJjRHaldb/OHLE6UPMrS/Osr7QkdlYoOtd3H5Zc8brJqy4bHbkyVbV93yaf14vgYwkK3xNtFM=
  bucket: draconpern-buildcache
  acl: public_read
  skip_cleanup: true
  local_dir: dpl_cd_upload 
