branches:
  only:
    - master

platform:
  - x86

configuration:
  - Release

install:
  - SET TYPE=%CONFIGURATION%
  - SET DEVSPACE=%APPVEYOR_BUILD_FOLDER%\..
  
# dcmtk & zlib
  - cd %DEVSPACE%
  - ps: |
      Invoke-WebRequest http://draconpern-buildcache.s3.amazonaws.com/dcmtk.7z -Outfile "dcmtk.7z"
  - 7z x -y dcmtk.7z

# openjpeg
  - cd %DEVSPACE%
  - git clone --branch=master https://github.com/uclouvain/openjpeg.git
  - cd openjpeg && git checkout openjpeg-2.1 && mkdir build-%TYPE% && cd build-%TYPE%
  - cmake .. -G "Visual Studio 11" -DBUILD_THIRDPARTY=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS_RELEASE="/MT /O2 /D NDEBUG" -DCMAKE_C_FLAGS_DEBUG="/D_DEBUG /MTd /Od" -DCMAKE_INSTALL_PREFIX=%DEVSPACE%\openjpeg\%TYPE%
  - msbuild /P:Configuration=%TYPE% INSTALL.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
 
before_build:
  - cd %APPVEYOR_BUILD_FOLDER% && mkdir build-%TYPE% && cd build-%TYPE%
  - cmake .. -G "Visual Studio 11" -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_FLAGS_RELEASE="/MT /O2 /D NDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="/D_DEBUG /MTd /Od" -DOPENJPEG=%DEVSPACE%\openjpeg\%TYPE% -DDCMTK_DIR=%DEVSPACE%\dcmtk\build-%TYPE% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\%TYPE%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build-%TYPE%
  - msbuild /P:Configuration=%TYPE% INSTALL.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cd %DEVSPACE%
  - 7z a fmjpeg2koj.7z fmjpeg2koj\%TYPE% openjpeg\%TYPE%
  - mv fmjpeg2koj.7z %APPVEYOR_BUILD_FOLDER%

artifacts:
  - path: fmjpeg2koj.7z
    name: fmjpeg2koj
 
deploy:
  provider: S3
  access_key_id:
    secure: ocfx3RWVSyFaLRBBJXRLrvwqFGoftzrWzqUWrx20/bc=
  secret_access_key:
    secure: cVrRAHZDL4OZaPmgpH2RAa6yKD1ckjrMvtL/RozVMTTxiMWe5+3BKGrWv7RzNQLK
  bucket: draconpern-buildcache
  set_public: true
  folder: 
  artifact: fmjpeg2koj    